# Generated by Django 6.0.2 on 2026-02-21 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("training_date", models.DateTimeField(auto_now_add=True)),
                ("epochs", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-training_date"],
            },
        ),
        migrations.CreateModel(
            name="StressRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("angry", "Angry"),
                            ("disgusted", "Disgusted"),
                            ("fearful", "Fearful"),
                            ("happy", "Happy"),
                            ("neutral", "Neutral"),
                            ("sad", "Sad"),
                            ("surprised", "Surprised"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stress_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "source",
                    models.CharField(
                        choices=[("image", "Image Upload"), ("live", "Live Camera")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                ("angry_score", models.FloatField(default=0.0)),
                ("disgusted_score", models.FloatField(default=0.0)),
                ("fearful_score", models.FloatField(default=0.0)),
                ("happy_score", models.FloatField(default=0.0)),
                ("neutral_score", models.FloatField(default=0.0)),
                ("sad_score", models.FloatField(default=0.0)),
                ("surprised_score", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
