# Generated by Django 4.2 on 2026-03-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stress_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Employee ID"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Engineering", "Engineering"),
                            ("Software Dev", "Software Development"),
                            ("QA & Testing", "QA & Testing"),
                            ("DevOps", "DevOps"),
                            ("Data Science", "Data Science"),
                            ("Product", "Product Management"),
                            ("Design", "Design & UX"),
                            ("HR", "Human Resources"),
                            ("Finance", "Finance"),
                            ("Sales", "Sales & Marketing"),
                            ("Support", "Customer Support"),
                            ("Management", "Management"),
                            ("Other", "Other"),
                        ],
                        default="Engineering",
                        max_length=50,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Designation / Role"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Phone Number"
                    ),
                ),
                (
                    "date_of_join",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Joining"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("link", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ModelMetrics",
        ),
        migrations.RemoveField(
            model_name="stressrecord",
            name="image",
        ),
        migrations.RemoveField(
            model_name="stressrecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="stressrecord",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="stressrecord",
            name="user",
        ),
        migrations.AlterField(
            model_name="stressrecord",
            name="source",
            field=models.CharField(
                choices=[("live", "Live"), ("image", "Image")],
                default="live",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stressrecord",
            name="stress_level",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stressrecord",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="stressrecord",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stress_app.employee",
            ),
        ),
    ]
